import { Router } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import plansRouter from "./plans.js";
import investmentsRouter from "./investments.js";
import transactionsRouter from "./transactions.js";
import walletsRouter from "./wallets.js";
import walletConnectRouter from "./walletConnect.js";
import settingsRouter from "./settings.js";
import dashboardRouter from "./dashboard.js";
import verificationRouter from "./verifications.js";
const router = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(plansRouter);
router.use(investmentsRouter);
router.use(transactionsRouter);
router.use(walletsRouter);
router.use(walletConnectRouter);
router.use(settingsRouter);
router.use(dashboardRouter);
router.use(verificationRouter);
export default router;
